application: demetertest-1054
version: 1
runtime: go
api_version: go1

handlers:
- url: /app/.*
  script: _go_app

- url: /index.html
  static_files: site/index.html
  upload: site/index.html

- url: /css
  static_dir: site/css

- url: /img
  static_dir: site/img

- url: /js
  static_dir: site/js
